# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('config.py', '.'),
        ('requirements.txt', '.'),
        ('env.example', '.'),
        ('BATCH_DOWNLOAD_GUIDE.md', '.'),
        ('PROJECT_STRUCTURE.md', '.'),
    ],
    hiddenimports=[
        'flask',
        'mutagen',
        'mutagen.mp3',
        'mutagen.id3',
        'yt_dlp',
        'dotenv',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'certifi',
        'charset_normalizer',
        'idna',
        'requests',
        'urllib3',
        'cryptography',
        'cffi',
        'pycparser',
        'six',
        'python_dateutil',
        'pytz',
        'babel',
        'markupsafe',
        'jinja2',
        'werkzeug',
        'flask',
        'mutagen',
        'yt_dlp',
        'dotenv',
        'utils',
        'models',
        'services',
        'controllers',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Bilibili2Navidrome',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/favicon.ico' if os.path.exists('static/favicon.ico') else None,
)